language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

install:
  - yarn install

before_deploy:
  - yarn install
  - yarn run generate
  - rm -rf node_modules/

jobs:
  include:
    - stage: tests
      name: "Lint"
      script: yarn run lint
    - stage: deploy
      if: branch = master
      name: "Deploy to gh-pages"
      script: skip
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUBTOKEN
        keep-history: true
        local_dir: dist
        fqdn: roadmap.opendevufcg.org
        on:
           branch: master